# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Hackathon_Tks' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Hackathon_Tks
  pod 'SnapKit'
  pod 'RealmSwift'
  pod 'MBProgressHUD'
  pod 'AlamofireImage'
end
